from __future__ import annotations
"""Automatic scientific report generation."""


from pathlib import Path
from datetime import datetime


def create_report(
    output: str | Path,
    title: str = "HydroMatAI - Electronic and Optical Properties",
    electronic_text: str = "",
    optical_text: str = "",
    convergence_text: str = "",
):

    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)

    text = f"""
{title}
============================================================

Generated by HydroMatAI
Date: {datetime.now().isoformat(timespec="seconds")}

1. ELECTRONIC PROPERTIES
------------------------------------------------------------

{electronic_text}

2. OPTICAL PROPERTIES
------------------------------------------------------------

{optical_text}

3. CONVERGENCE ANALYSIS
------------------------------------------------------------

{convergence_text}

4. SCIENTIFIC INTERPRETATION
------------------------------------------------------------

Electronic properties describe the electronic structure,
density of states and band-gap behaviour.

Optical properties describe the response of the material
to electromagnetic excitation through the dielectric
function, refractive index, extinction coefficient and
reflectivity.

These interpretations must be associated with the
corresponding Quantum ESPRESSO calculation parameters
and convergence criteria before publication.

============================================================
"""

    output.write_text(
        text.strip() + "\n",
        encoding="utf-8",
    )

    return output
